### ISSUE TITLE
Rendering on the Cutout and Transparent Layers together interferes with water rendering

### ISSUE THREAD

**Issue by Codasylph** [grondag/json-model-extensions#3] opened 2019-07-01 00:37 UTC
When using jmx to render a block with both translucent and cutout textures, water which is in the same chunk and has a larger z coordinate than the block in question may not be rendered.

![2019-06-30_19 53 18](https://user-images.githubusercontent.com/13297433/60404366-4524da00-9b76-11e9-8c64-20185320752b.png)

here's the json model for one such block
https://hastebin.com/usugirejes.json

all of the blocks in question return `BlockRenderLayer.CUTOUT` in `getRenderLayer()`

Minecraft: 1.14.3
fabric api: 0.3.0+build.187
jmx: 0.2.3+build.45

**Comment by Codasylph** [comment] 2019-07-01 01:12
So, for shits and giggles I also tried making simpler test block that is a full block with one little bit that is translucent a la the redstone example in jmx's test pack and this produces the same bug.
 this is the model and textures I used.
https://hastebin.com/akimitiqum.json
![test_full](https://user-images.githubusercontent.com/13297433/60405029-af8c4900-9b7b-11e9-8fcf-9f36b13deffd.png)
![test_solid](https://user-images.githubusercontent.com/13297433/60405032-b2873980-9b7b-11e9-9323-a4f4845201f1.png)
![test_translucent](https://user-images.githubusercontent.com/13297433/60405033-b2873980-9b7b-11e9-925c-5a55c4b4f036.png)

**Comment by grondag** [comment] 2019-07-01 02:06
Can't reproduce.  https://imgur.com/a/w7XTUU3

My block code is simply this:

```java
Block multiBlock = new Block(FabricBlockSettings.of(Material.STONE).strength(1, 1).build()) {
            @Override
            public BlockRenderLayer getRenderLayer() {
                return BlockRenderLayer.CUTOUT;
            }
        };
```

Anything else I should add?

**Comment by Codasylph** [comment] 2019-07-01 03:45
Yeah, i don't think your code is the problem.  My code for the test block i did is just:
`public static final Block TEST_BLOCK = new Block(FabricBlockSettings.copy(Blocks.GLASS).build());`

But I've noticed it doesn't *always* do the glitch and sometimes placing other blocks makes it unglitch.
https://streamable.com/vzar4

**Comment by Codasylph** [comment] 2019-07-01 05:11
So.. In an effort to prove  to myself that I am not crazy, and also that it isn't secretly my mod causing this bug, I went ahead and made a separate mod project that only includes itself, fabric, and jmx and just adds the one test block and the issue still persists.  I felt silly putting that project up on github, so here's a link to a zip of the project folder in my drop box, complete with a world save that has the test block placed near water to specifically demonstrate the issue.  If it's not reproduce-able from this.. then.. I might just actually be crazy.
https://www.dropbox.com/s/3yyp33x75bumjoz/jmx-test-mod.zip?dl=0

**Comment by grondag** [comment] 2019-07-01 13:18
Thank you so, so much for this.  Able to reproduce now.

**Comment by grondag** [comment] 2019-07-01 22:54
FYI haven’t run this down yet but very, very likely it is an Indigo defect vs a problem with JMX. It would likely happen even if using the renderer API directly.  I’ll open the defect for Indigo when I’ve isolated it and make a test build available when there is a fix. 

Haven’t tested Canvas renderer yet.

**Comment by Codasylph** [comment] 2019-07-01 22:55
Fun times! I guess in that case I'll start looking into Canvas.

**Comment by grondag** [comment] 2019-07-02 15:27
Confirmed that Canvas doesn't have the problem.  However, it is [not rendering cutout+translucent correctly](https://github.com/grondag/canvas/issues/34). (The translucent layer is missing in terrain.)  That will also be fixed.

**Comment by grondag** [comment] 2019-07-06 02:36
FYI, [Fabric PR #295](https://github.com/FabricMC/fabric/pull/295) has been submitted to resolve this problem and a test build is available [here](https://github.com/grondag/fabric/releases/tag/indigo-0.1.8-rc0).

**Comment by grondag** [comment] 2019-07-07 23:07
Should be resolved in the latest release of Indigo.  See https://github.com/FabricMC/fabric/pull/295.

**Closed by grondag** 2019-07-07 23:07 UTC
